Implement retry

diff --git a/.github/workflows/node.yml b/.github/workflows/node.yml
--- a/.github/workflows/node.yml
+++ b/.github/workflows/node.yml
@@ -10,6 +10,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     strategy:
+      fail-fast: false
       matrix:
         node: [ 20, 22, 24 ]
     steps:
@@ -29,7 +30,19 @@ jobs:
         run: npm run lint
 
       - name: Test
-        run: npm run test
+        env:
+          MAX_RETRIES: ${{ vars.MAX_RETRIES }}
+          RETRY_DELAY: ${{ vars.RETRY_DELAY }}
+        run: |
+          until npm run test; do
+            ATTEMPTS=$((ATTEMPTS + 1))
+            if [ "$ATTEMPTS" -ge $MAX_RETRIES ]; then
+              echo "Tests failed after $MAX_RETRIES attempts."
+              exit 1
+            fi
+            echo "Test failed, retrying in $RETRY_DELAY seconds... ($ATTEMPTS/$MAX_RETRIES)"
+            sleep $RETRY_DELAY
+          done
 
       - name: Build
         run: npm run build
